config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resource :events
    end
  end

  resources :bonums

  resources :achievements do
    member do
      get 'fine'
      get 'undo'
    end
  end

  resources :requirements

  resources :badges

  resources :templates

  get 'templates/by/:scope', to: 'templates#scope'
  # get 'events/template', to: 'events#from_template'

  get 'site/about'

  get 'site/terms'

  get 'site/privacy'

  get 'site/contact'

  get 'calendar/index'
  get 'boys/advance'
  get '/boys/:id/promote', to: 'boys#promote', as: 'boy_promote'
  get '/boys/:boy_id/record/:key', to: 'ranks#record', as: 'rank_record'

  resources :events

  resources :events do 
    resources :attendances do
      member do 
        get 'add'
        get 'del'
      end
    end
    collection do 
      get :take_attendance
      get :get_events
      post :move
      post :resize
    end
  end

  resources :packs

  resources :attendances

  resources :patrols

  resources :boys do 
    resources :bonums
  end

  resources :ranks

  resources :locations

  root :to => "boys#index"
  devise_for :users 
  resources :users
end

app/views/templates/_form.html.haml
= simple_form_for(@template) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :heritage
    = f.input :hobbies
    = f.input :outdoor_activities
    = f.input :pioneer_skills
    = f.input :sci_tech
    = f.input :life_skills
    = f.input :values
    = f.input :life_skills
    = f.input :service
    = f.input :rank

  .form-actions
    = f.button :submit

app/views/templates/_header.html.haml
%table.table.table-bordered
  %tr
    %th Event
    %th <abbr title='Service Hours'>S</abbr>
    %th <abbr title='Heritage'>H</abbr>
    %th <abbr title='Hobbies'>B</abbr>
    %th <abbr title='Life Skills'>L</abbr>
    %th <abbr title='Outdoor Activities'>O</abbr>
    %th <abbr title='Pioneering Skills'>P</abbr>
    %th <abbr title='Science & Technology'>T</abbr>
    %th <abbr title='Values'>V</abbr>

app/views/templates/_template.html.haml
%tr
  %td.col.s4
    %strong= link_to "#{rank.to_s.titleize} - #{template.name}", template
    %p= template.description || 'No template Description.'
    %p= link_to "Create Event with this Template", new_event_path() + "?tid=#{template.id}", :target => "_blank"

  %td.col.s1.center-align.service=             tooltip(bif(template.service,""), 'Service')
  %td.col.s1.center-align.heritage=            tooltip(bif(template.heritage,""), 'Heritage')
  %td.col.s1.center-align.hobbies=             tooltip(bif(template.hobbies,""), 'Hobbies')
  %td.col.s1.center-align.life_skills=         tooltip(bif(template.life_skills,""), 'Life Skills')
  %td.col.s1.center-align.outdoor_activities=  tooltip(bif(template.outdoor_activities,""), 'Outdoor')
  %td.col.s1.center-align.pioneer_skills=      tooltip(bif(template.pioneer_skills,""), 'Pioneer')
  %td.col.s1.center-align.sci_tech=            tooltip(bif(template.sci_tech,""), 'Sci & Tech')
  %td.col.s1.center-align.values=              tooltip(bif(template.values,""), 'Values')

app/views/templates/edit.html.haml
%h1 Editing template

= render 'form'

= link_to 'Show', @template
\|
= link_to 'Back', templates_path

app/views/templates/index.html.haml
.row.valign-wrapper
  .col.s12.m8.valign
    =title("Templates")

    %dd
      %dt Note:
      %dd hover your cursor over the heading for a more complete description of the branch.

  .col.s12.m4.valign.right-align
    = link_to micon('add'), new_template_path, {class: 'btn-floating btn-large waves-effect waves-light'} if can? :create, Template

%ul#toc
  %li= link_to "Fox Templates", "#fox"
  %li= link_to "Hawk Templates", "#hawk"
  %li= link_to "Lion Templates", "#lion"

- [:fox, :hawk, :lion].each do |rank|
  %h2{:id => rank.to_s}
    = rank.to_s.titleize
    Event Templates

  %p
    To use a template to create an event, click the "Create Event from Template" link. That will open a new window and create the event. You will then need to edit the date to coincide with when you scheduled the templated event.

  %ul
    %li= link_to "Back to top", "#toc"
    %li= link_to "Fox Templates", "#fox"
    %li= link_to "Hawk Templates", "#hawk"
    %li= link_to "Lion Templates", "#lion"


  %table.striped.bordered.dev
    %thead
      %tr
        %th.col.s4 Event
        =render :partial => 'shared/leaf_header'
    %tbody
      = render :partial => @templates[rank], :locals => {:rank => rank}

= link_to 'New Template', new_template_path, :class => "btn btn-primary"

app/views/templates/new.html.haml
%h1 New template

= render 'form'

= link_to 'Back', templates_path

app/views/templates/show.html.haml
=title("Template: #{@template.rank} - #{@template.name}" )


= link_to "Edit #{@template.name}", edit_template_path(@template), :class => "btn btn-primary" if can? :edit, @template

%h3 Leaves

%table.table
  = leaf_header_full(@template)

%h3 Description

%p= @template.description || "No Description"

= link_to "Create Event with this Template", new_event_path(template_params(@template)), :class => "btn btn-primary"