config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resource :events
    end
  end

  resources :bonums

  resources :achievements do
    member do
      get 'fine'
      get 'undo'
    end
  end

  resources :requirements

  resources :badges

  resources :templates

  get 'templates/by/:scope', to: 'templates#scope'
  # get 'events/template', to: 'events#from_template'

  get 'site/about'

  get 'site/terms'

  get 'site/privacy'

  get 'site/contact'

  get 'calendar/index'
  get 'boys/advance'
  get '/boys/:id/promote', to: 'boys#promote', as: 'boy_promote'
  get '/boys/:boy_id/record/:key', to: 'ranks#record', as: 'rank_record'

  resources :events

  resources :events do 
    resources :attendances do
      member do 
        get 'add'
        get 'del'
      end
    end
    collection do 
      get :take_attendance
      get :get_events
      post :move
      post :resize
    end
  end

  resources :packs

  resources :attendances

  resources :patrols

  resources :boys do 
    resources :bonums
  end

  resources :ranks

  resources :locations

  root :to => "boys#index"
  devise_for :users 
  resources :users
end

app/models/badge.rb
class Badge < ActiveRecord::Base
  extend FriendlyId

  # belongs_to :rank
  friendly_id :name, use: [:slugged, :finders]
  has_many :requirements
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :set_badge, only: [:show, :edit, :update, :destroy]

  # GET /badges
  # GET /badges.json
  def index
    @badges = Badge.all
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
  end

  # GET /badges/new
  def new
    @badge = Badge.new
  end

  # GET /badges/1/edit
  def edit
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(badge_params)

    respond_to do |format|
      if @badge.save
        format.html { redirect_to @badge, notice: 'Badge was successfully created.' }
        format.json { render :show, status: :created, location: @badge }
      else
        format.html { render :new }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /badges/1
  # PATCH/PUT /badges/1.json
  def update
    respond_to do |format|
      if @badge.update(badge_params)
        format.html { redirect_to @badge, notice: 'Badge was successfully updated.' }
        format.json { render :show, status: :ok, location: @badge }
      else
        format.html { render :edit }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge.destroy
    respond_to do |format|
      format.html { redirect_to badges_url, notice: 'Badge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_badge
      @badge = Badge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def badge_params
      params.require(:badge).permit(:name, :description, :rank_id)
    end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/badges/_form.html.haml
= simple_form_for(@badge) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description
    = f.association :rank

  .form-actions
    = f.button :submit

app/views/badges/edit.html.haml
%h1 Editing badge

= render 'form'

= link_to 'Show', @badge
\|
= link_to 'Back', badges_path

app/views/badges/index.html.haml
%h1 Listing badges

%table
  %tr
    %th Name
    %th Description
    %th Rank
    %th
    %th
    %th

  - @badges.each do |badge|
    %tr
      %td= badge.name
      %td= badge.description
      %td= badge.rank
      %td= link_to 'Show', badge
      %td= link_to 'Edit', edit_badge_path(badge)
      %td= link_to 'Destroy', badge, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Badge', new_badge_path

app/views/badges/new.html.haml
%h1 New badge

= render 'form'

= link_to 'Back', badges_path

app/views/badges/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @badge.name
%p
  %b Description:
  = @badge.description
%p
  %b Rank:
  = @badge.rank

= link_to 'Edit', edit_badge_path(@badge)
\|
= link_to 'Back', badges_path