config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resource :events
    end
  end

  resources :bonums

  resources :achievements do
    member do
      get 'fine'
      get 'undo'
    end
  end

  resources :requirements

  resources :badges

  resources :templates

  get 'templates/by/:scope', to: 'templates#scope'
  # get 'events/template', to: 'events#from_template'

  get 'site/about'

  get 'site/terms'

  get 'site/privacy'

  get 'site/contact'

  get 'calendar/index'
  get 'boys/advance'
  get '/boys/:id/promote', to: 'boys#promote', as: 'boy_promote'
  get '/boys/:boy_id/record/:key', to: 'ranks#record', as: 'rank_record'

  resources :events

  resources :events do 
    resources :attendances do
      member do 
        get 'add'
        get 'del'
      end
    end
    collection do 
      get :take_attendance
      get :get_events
      post :move
      post :resize
    end
  end

  resources :packs

  resources :attendances

  resources :patrols

  resources :boys do 
    resources :bonums
  end

  resources :ranks

  resources :locations

  root :to => "boys#index"
  devise_for :users 
  resources :users
end

app/models/patrol.rb
class Patrol < ActiveRecord::Base
  belongs_to :pack
  has_many :boys
  validates_presence_of :name
  validates_presence_of :rank
end

app/controllers/patrols_controller.rb
class PatrolsController < ApplicationController
  before_action :set_patrol, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /patrols
  # GET /patrols.json
  def index
    @patrols = Patrol.all
  end

  # GET /patrols/1
  # GET /patrols/1.json
  def show
  end

  # GET /patrols/new
  def new
    @patrol = Patrol.new
  end

  # GET /patrols/1/edit
  def edit
  end

  # POST /patrols
  # POST /patrols.json
  def create
    @patrol = Patrol.new(patrol_params)

    respond_to do |format|
      if @patrol.save
        format.html { redirect_to @patrol, notice: 'Patrol was successfully created.' }
        format.json { render :show, status: :created, location: @patrol }
      else
        format.html { render :new }
        format.json { render json: @patrol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patrols/1
  # PATCH/PUT /patrols/1.json
  def update
    respond_to do |format|
      if @patrol.update(patrol_params)
        if @patrol.rank.nil?
          @patrol.rank = @patrol.name.downcase
          @patrol.save
        end
        format.html { redirect_to @patrol, notice: 'Patrol was successfully updated.' }
        format.json { render :show, status: :ok, location: @patrol }
      else
        format.html { render :edit }
        format.json { render json: @patrol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patrols/1
  # DELETE /patrols/1.json
  def destroy
    @patrol.destroy
    respond_to do |format|
      format.html { redirect_to patrols_url, notice: 'Patrol was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patrol
      @patrol = Patrol.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patrol_params
      params.require(:patrol).permit(:name, :pack_id, :rank)
    end
end

app/helpers/patrols_helper.rb
module PatrolsHelper
end

app/views/patrols/_form.html.haml
= simple_form_for(@patrol) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.association :pack

  .form-actions
    = f.button :submit

app/views/patrols/edit.html.haml
%h1 Editing patrol

= render 'form'

= link_to 'Show', @patrol
\|
= link_to 'Back', patrols_path

app/views/patrols/index.html.haml
%h1 Listing patrols

%table
  %tr
    %th Name

  - @patrols.each do |patrol|
    %tr
      %td= link_to patrol.name, patrol

%br

= link_to 'New Patrol', new_patrol_path

app/views/patrols/new.html.haml
%h1 New patrol

= render 'form'

= link_to 'Back', patrols_path

app/views/patrols/show.html.haml
%h1= "#{@patrol.pack.name}: #{@patrol.name}"

%ul.list-group
  - @patrol.boys.each do |d|
    %li.list-group-item= link_to d.name, d.becomes(Boy)

= link_to 'Edit', edit_patrol_path(@patrol)
\|
= link_to 'Back', patrols_path