config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resource :events
    end
  end

  resources :bonums

  resources :achievements do
    member do
      get 'fine'
      get 'undo'
    end
  end

  resources :requirements

  resources :badges

  resources :templates

  get 'templates/by/:scope', to: 'templates#scope'
  # get 'events/template', to: 'events#from_template'

  get 'site/about'

  get 'site/terms'

  get 'site/privacy'

  get 'site/contact'

  get 'calendar/index'
  get 'boys/advance'
  get '/boys/:id/promote', to: 'boys#promote', as: 'boy_promote'
  get '/boys/:boy_id/record/:key', to: 'ranks#record', as: 'rank_record'

  resources :events

  resources :events do 
    resources :attendances do
      member do 
        get 'add'
        get 'del'
      end
    end
    collection do 
      get :take_attendance
      get :get_events
      post :move
      post :resize
    end
  end

  resources :packs

  resources :attendances

  resources :patrols

  resources :boys do 
    resources :bonums
  end

  resources :ranks

  resources :locations

  root :to => "boys#index"
  devise_for :users 
  resources :users
end

app/models/event.rb
class Event < ActiveRecord::Base
  include ActiveModel::Validations
  include PublicActivity::Common

  acts_as_paranoid

  attr_accessor :period, :frequency, :commit_button

  belongs_to :location
  scope :before, lambda {|end_time|  {:conditions => ["ends_at < ?", Event.format_date(end_time)] }}
  scope :after, lambda {|start_time| {:conditions => ["starts_at > ?", Event.format_date(start_time)] }}

  has_many :attendances
  has_many :boys, through: :attendances
  
  validates_presence_of :name, :description, :starts_at
  # validate :validate_leaf_count
  # validates_with EventValidator
  validate :validate_timings
  
  belongs_to :event_series
  
  REPEATS = [
    "Does not repeat",
    "Daily"          ,
    "Weekly"         ,
    "Monthly"        ,
    "Yearly"         
  ]
  def active_attendances
    them = self.attendances.map do
      |a| next if a.boy.nil?;
      a if a.boy.active? 
    end.compact
    # raise them.inspect
  end
  def leaf_count
    return [heritage, hobbies, life_skills, outdoor_activities, pioneer_skills, sci_tech, values ].inject(:+)
  end  
  def validate_timings
    if (starts_at.nil?)# or ends_at.nil?)
      errors[:base] << "Can't have an event without a start time."
      # return
    # elsif (starts_at >= ends_at) and !all_day
    #   errors[:base] << "Start Time must be less than End Time"
    end
  end
  def address
    return  "No Address Given" if location.nil?
    return location.address
  end
  
  def update_events(events, event)
    events.each do |e|
      begin 
        st, et = e.starts_at, e.ends_at
        e.attributes = event
        if event_series.period.downcase == 'monthly' or event_series.period.downcase == 'yearly'
          nst = DateTime.parse("#{e.starts_at.hour}:#{e.starts_at.min}:#{e.starts_at.sec}, #{e.starts_at.day}-#{st.month}-#{st.year}")  
          net = DateTime.parse("#{e.ends_at.hour}:#{e.ends_at.min}:#{e.ends_at.sec}, #{e.ends_at.day}-#{et.month}-#{et.year}")
        else
          nst = DateTime.parse("#{e.starts_at.hour}:#{e.starts_at.min}:#{e.starts_at.sec}, #{st.day}-#{st.month}-#{st.year}")  
          net = DateTime.parse("#{e.ends_at.hour}:#{e.ends_at.min}:#{e.ends_at.sec}, #{et.day}-#{et.month}-#{et.year}")
        end
        #puts "#{nst}           :::::::::          #{net}"
      rescue
        nst = net = nil
      end
      if nst and net
        #          e.attributes = event
        e.starts_at, e.ends_at = nst, net
        e.save
      end
    end
    
    # event_series.attributes = event
    # event_series.save
  end

  # need to override the json view to return what full_calendar is expecting.
  # http://arshaw.com/fullcalendar/docs/event_data/Event_Object/
  def xas_json(options = {})
    {
      :id => self.id,
      :title => self.title,
      :description => self.description || "",
      :start => starts_at.rfc822,
      :end => ends_at.rfc822,
      :allDay => self.all_day,
      :recurring => false,
      :url => Rails.application.routes.url_helpers.event_path(id)
    }
    
  end
  def self.format_date(date_time)
    Time.at(date_time.to_i).to_formatted_s(:db)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_wide_view
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :breadcrumb, only: [:show, :edit, :new]
  load_and_authorize_resource 

  def breadcrumb
    add_breadcrumb "Events", events_path, :title => "Back to the Events List"  
    add_breadcrumb @event.name if @event
  end
  def from_template
    raise params.permit('name', 'description', 'starts_at', 'ends_at', 'all_day', 'period', 'frequency', 'commit_button', :service, :heritage, :hobbies, :hobbies, :life_skills, :outdoor_activities, :pioneer_skills, :sci_tech, :values, :location_id)
  end
  def new
    if params[:tid]
      template = Template.find(params[:tid])
      name = [template.rank, Date.today.year, template.name].join(" - ")
      p = {
        :name => name,
        :location_id => 1,
        :life_skills => template.life_skills.to_i || 0,
        :heritage => template.heritage.to_i || 0,
        :hobbies => template.hobbies.to_i || 0,
        :pioneer_skills => template.pioneer_skills.to_i || 0,
        :life_skills => template.life_skills.to_i || 0,
        :values => template.values.to_i || 0,
        :outdoor_activities => template.outdoor_activities.to_i || 0,
        :period => "Does not repeat",
        :description => "Cloned from Template: #{name}",
        :starts_at => (DateTime.now.change(hour: 18)).strftime('%Y-%m-%d %H:%M')
       }
       respond_to do |format|
         @event = Event.create(p)
         format.html { redirect_to edit_event_path(@event), notice: 'event was successfully updated.' }
       end
     end
    @event = Event.new
  end
  
  def take_attendance
    @title = "Taking Attendance"
    @events = Event.where(starts_at: 7.days.ago..(Time.now.midnight + 4.hours)).sort_by(&:starts_at).reverse
    render :index
  end
  def create
    event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        @event.create_activity :create, owner: current_user

      # raise "GOOD:" + @event.inspect
        format.html { redirect_to event_url @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        
      # raise "Bad:" + @event.inspect
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
        # render :text => event.errors.full_messages.to_sentence, :status => 422
      end
    end
  end
  
  def index
    @title = "Events"
    @events = Event.order(:starts_at).reverse_order.page params[:page]
  end
  def get_events
    @events = Event.find(:all, :conditions => ["starts_at >= '#{Time.at(params['start'].to_i).to_formatted_s(:db)}' and ends_at <= '#{Time.at(params['end'].to_i).to_formatted_s(:db)}'"] )
    events = [] 
    @events.each do |event|
      events << {:id => event.id, :title => event.title, :description => event.description || "Some cool description here...", :start => "#{event.starts_at.iso8601}", :end => "#{event.ends_at.iso8601}", :allDay => event.all_day, :recurring => (event.event_series_id)? true: false}
    end
    render :text => events.to_json
  end
  
  def move
    @event = Event.find_by_id params[:id]
    if @event
      @event.starts_at = (params[:minute_delta].to_i).minutes.from_now((params[:day_delta].to_i).days.from_now(@event.starts_at))
      # @event.ends_at = (params[:minute_delta].to_i).minutes.from_now((params[:day_delta].to_i).days.from_now(@event.ends_at))
      @event.all_day = params[:all_day]
      @event.save
    end
    render :nothing => true
  end
  
  
  def resize
    @event = Event.find_by_id params[:id]
    if @event
      # @event.ends_at = (params[:minute_delta].to_i).minutes.from_now((params[:day_delta].to_i).days.from_now(@event.ends_at))
      @event.save
    end    
    render :nothing => true
  end
  
  def edit
    @event = Event.find_by_id(params[:id])
    # render :json => { :form => render_to_string(:partial => 'edit_form') } 
  end
  def show
    
    @attendees = @event.attendances.sort_by { |a| a.boy.lastnamefirst }.map {|a| a if a.boy.active?}.compact

    find_candidates
  end
  def update
    # raise params.inspect
    # @event = Event.find_by_id(params[:event][:id])
    # if params[:event][:commit_button] == "Update All Occurrence"
    #   @events = @event.event_series.events #.find(:all, :conditions => ["starts_at > '#{@event.starts_at.to_formatted_s(:db)}' "])
    #   @event.update_events(@events, event_params)
    # elsif params[:event][:commit_button] == "Update All Following Occurrence"
    #   @events = @event.event_series.events.find(:all, :conditions => ["starts_at > '#{@event.starts_at.to_formatted_s(:db)}' "])
    #   @event.update_events(@events, event_params)
    # else
    #   @event.update_events(@events, event_params)
    # end
    # render :show    
    respond_to do |format|
      if @event.update(event_params)
        @event.attendances.each do |a|
          a.boy.recalcuate_leaves
        end
        @event.create_activity :update, owner: current_user
        format.html { redirect_to @event, notice: 'event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
  def template
    @template = Template.find(params[:template_id])
    # raise @template.inspect
  end
  
  def destroy
    @event = Event.find_by_id(params[:id])
    

    if params[:delete_all] == 'true'
      @event.event_series.destroy
    elsif params[:delete_all] == 'future'
      @events = @event.event_series.events.find(:all, :conditions => ["starts_at > '#{@event.starts_at.to_formatted_s(:db)}' "])
      @event.event_series.events.delete(@events)
    else
      @event.attendances.delete_all
      @event.destroy
    end
    Boy.all.each do |boy|
      boy.recalcuate_leaves
    end
    
    @event.create_activity :destroy, owner: current_user
    redirect_to :action => 'index' 
  end

  private
    def event_params
      # params.require(:event).permit('name' ,'location_id' ,'heritage' ,'hobbies' ,'life_skills' ,'outdoor_activities' ,'pioneer_skills' ,'sci_tech' ,'values' ,'service' ,'starts_at' ,'description')
      params.require(:event).permit('name', 'description', 'starts_at', 'all_day', 'period', 'frequency', 'commit_button', :service, :heritage, :hobbies, :hobbies, :life_skills, :outdoor_activities, :pioneer_skills, :sci_tech, :values, :location_id)    
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end
end

app/helpers/events_helper.rb
module EventsHelper
	def leaf_form(f,branch)
		c = f.text_field branch
		c += f.label branch
		c
		# return f.input branch.to_sym, as: :select, :item_wrapper_class => 'inline', collection: [0,1,2,3,5 ], default: 0
	end
	def event_dtg(e)
		start = e.starts_at.strftime('%d %b %Y @ %H:%M')
		return start.html_safe
		if e.starts_at + 4.hours < e.ends_at
			# start = e.starts_at.strftime('%d %b %Y @ %H:%M')
			finish = "&ndash;" + e.ends_at.strftime('%d %b %Y')
		else
			# start = e.starts_at.strftime('%d %b %Y')
		end
		return "#{start}#{finish}".html_safe
		# return e.starts_at.strftime('%d %b %Y')
	end
	def leaf_list(obj)
		output = [
			["Svc", "Service", obj.service],
			["Hrg", "Heritage", obj.heritage],
			["Hob", "Hobbies", obj.hobbies],
			["Lif", "Life Skills", obj.life_skills],
			["Out", "Outdoor Activities", obj.outdoor_activities],
			["Pin", "Pioneer Skills", obj.pioneer_skills],
			["S&T", "Science & Technology", obj.sci_tech],
			["Val", "Values", obj.values	]	
		].map do |leaf|
			next if leaf.last.nil? or leaf.last.zero?
			"#{leaf[1]}  (#{leaf.last})"
		end
		return output.join("\n").html_safe
	end
	def leaf_header(obj)
		output = [
			["Svc", "Service", obj.service],
			["Hrg", "Heritage", obj.heritage],
			["Hob", "Hobbies", obj.hobbies],
			["Lif", "Life Skills", obj.life_skills],
			["Out", "Outdoor Activities", obj.outdoor_activities],
			["Pin", "Pioneer Skills", obj.pioneer_skills],
			["S&T", "Science & Technology", obj.sci_tech],
			["Val", "Values", obj.values	]	
		].map do |leaf|
			next if leaf.last.nil? or leaf.last.zero?
			"<div class='col s12 m4'><b>#{leaf[1].titlecase}:</b> #{leaf.last}</div>"
		end
		return "#{output.join("\n")}".html_safe
	end
	def leaf_list_item(obj)
		output = [
			["Service", obj.service],
			["Heritage", obj.heritage],
			["Hobbies", obj.hobbies],
			["Life Skills", obj.life_skills],
			["Outdoor Activities", obj.outdoor_activities],
			["Pioneer Skills", obj.pioneer_skills],
			["Science & Technology", obj.sci_tech],
			["Values", obj.values	]	
		].map do |leaf|
			next if leaf.last.nil? or leaf.last.zero?
			"<li class='list-group-item'>#{leaf.first.titlecase} (#{leaf.last})</li>"
		end
		return output.join("\n").html_safe
	end
	def leaf_header_full(obj)
		output = [
			["Service", obj.service],
			["Heritage", obj.heritage],
			["Hobbies", obj.hobbies],
			["Life Skills", obj.life_skills],
			["Outdoor Activities", obj.outdoor_activities],
			["Pioneer Skills", obj.pioneer_skills],
			["Science & Technology", obj.sci_tech],
			["Values", obj.values	]	
		].map do |leaf|
			next if leaf.last.nil? or leaf.last.zero?
			"<tr><th>#{leaf.first.titlecase}</th><td>#{leaf.last}</td></tr>"
		end
		return output.join("\n").html_safe
	end
	def bif(i,d=nil)
		if i == 0
			return i if d.nil?
			return d
		end
		return "<strong>#{i}</strong>".html_safe
	end
end

app/views/events/_attendees.html.haml
=render :partial => attendees

app/views/events/_candidate.html.haml
%div{:class => "row candidate #{(get_row() % 2 == 0) ? 'even' : 'odd'}"}
  %div.col.s7= link_to candidate.name, candidate.becomes(Boy)
  %div.col.s3= candidate.patrol.name
  %div.col.s2
    = link_to micon('person_add'), add_event_attendance_path(@event.id, candidate.id), :remote => true, class: "btn" if can? :edit, @event
  - count_attendee()

app/views/events/_candidates.html.haml
- %w(fox hawk lion).each do |r|
  %h4= r.titleize
  = render :partial => 'events/candidate', :collection => @candidates[r.to_sym]

app/views/events/_event.html.haml
%tr
  %th.rel{:scope => 'row'}
    %strong= link_to event.name, event
    %span.badge= event.active_attendances.length
  %td.text-center= event.starts_at.strftime("%m/%d/%Y")
  %td.text-center.service= bif(event.service,"")
  %td.text-center.heritage= bif(event.heritage,"")
  %td.text-center.hobbies= bif(event.hobbies,"")
  %td.text-center.life_skills= bif(event.life_skills,"")
  %td.text-center.outdoor_activities= bif(event.outdoor_activities,"")
  %td.text-center.pioneer_skills= bif(event.pioneer_skills,"")
  %td.text-center.sci_tech= bif(event.sci_tech,"")
  %td.text-center.values= bif(event.values,"")

app/views/events/_form.html.haml
= form_for(@event) do |f|
  .card-panel
    %h4 Details
    .row
      .input-field.col.s12
        = f.text_field :name, :class => 'validate'
        = f.label :name
    .row
      .input-field.col.s12
        = f.text_field :starts_at, :class => 'datepicker validate'
        = f.label :starts_at
    .row
      .input-field.col.s12
        = f.text_area :description, :class => 'materialize-textarea'
        = f.label :description

  .card-panel  
    %h4 Leaves

    %p Branches explained in greater detail below the form.

    .row
      .input-field.col.s6.m3
        = leaf_form(f,:heritage)
      .input-field.col.s6.m3
        = leaf_form(f,:hobbies)
      .input-field.col.s6.m3
        = leaf_form(f,:life_skills)
      .input-field.col.s6.m3
        = leaf_form(f,:outdoor_activities)
    .row
      .input-field.col.s6.m3
        = leaf_form(f,:pioneer_skills)
      .input-field.col.s6.m3
        = leaf_form(f,:sci_tech)
      .input-field.col.s6.m3
        = leaf_form(f,:values)
      .input-field.col.s6.m3
        = f.text_field :service

    
    .row
      .col.s12
        = f.button :submit, :class => 'btn btn-primary'
        or
        = link_to "Cancel", :back

%h2 Branches Explained

%h3 Heritage Branch

%p An exploration of a boy’s own family heritage (Fox Patrol), American heritage (Hawk Patrol), and Christian heritage (Mountain Lion Patrol). Emphasis is placed on upholding the finest traditions of the heritage we obtain from our forefathers. This branch would include, but not be limited to, such items as visiting historical sites, learning about the early church, conducting genealogical research, and exploring American history.

%h3 Hobbies Branch

%p An exploration of various indoor and outdoor hobbies that demand varying levels of knowledge, skill, or aptitude. This branch would include, but not be limited to, such items as bowling, horticulture, photography, bird watching, model building, strategy games, creating collections, and art. Woodlands Trail program developers have responded to feedback that many hobbies are dependent on geographical areas, as well as the resources available to individual Trailmen. Therefore, additional latitude in local meeting planning has been incorporated into the program. Trail Guides are asked to plan and organize local events and overnight outings for Trailmen to learn about hobbies both common to many people and unique to the Troop’s geographical region. While some lesson plans involving hobbies have been provided, it is anticipated that most activities providing leaves for this branch would center on events planned by the local Trail Guide.

%h3 Life Skills Branch

%p Teaching life lessons ranging from the practical to higher-level interpersonal skill sets. This branch would include, but not be limited to, such items as food preparation, home or personal item repairs, construction, mechanics, public speaking, knowledge of safety practices, health and fitness, first aid, and dealing with difficult people or situations.

%h3 Outdoor Skills Branch

%p Having fun in the outdoors with sports and other activities. This branch would include, but not be limited to, such items as baseball, football, soccer, bicycling, track and field, and group or team games.

%h3 Pioneering Skills Branch

%p Gaining basic understanding of woodcraft, hiking, exploration, and camping skills. This branch would include, but not be limited to, such items as learning knots and lashings, proper use of knives (Mountain Lions only), Tread Lightly (outdoor principles), navigation, and plant/animal/hazard identification.

%h3 Sci & Tech Branch

%p An exploration of physical and natural science concerning our created world. Woodlands Trail program developers recognize the extreme importance of science and technology skills in life today. Entire schools are devoted to the study of Science, Technology, Engineering, and Math (S.T.E.M.). Trailmen would be more likely to benefit from hands-on events and overnight outings. Several meeting plans involving science and technology have been provided. Additional meetings providing leaves for this branch would involve outings to unique local sites. Trailmen could take advantage of such things as: science labs, factory tours, mines, beaches, ships, quarries, planetariums, museums, observatories, aquariums, hospitals, airports, aquaculture farms, veterinarian office, broadcasting stations, children’s hands- on science centers, nature centers, commercial caves, and farms. In the absence of these options, the Troop could plan science and technology fairs or other events to expose the boys to S.T.E.M. Trail Guides are expected to plan and organize these local opportunities.

%h3 Heritage Branch

%p Instilling biblically based values within the boys regarding any number of pertinent topics. A central focus of this branch are teachings of the Christian faith.

:javascript
  var input = $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    format: 'yyyy-mm-dd',
    selectYears: 15 // Creates a dropdown of 15 years to control year
  });
  var picker = input.pickadate('picker')

app/views/events/_header.html.haml
=title @event.name

.row
  .col.s8 &nbsp;
  .col.s2= link_to "<i class='material-icons'>mode_edit</i>".html_safe, edit_event_path(@event), :class => "btn waves-effect waves-light" if can? :edit, @event
  .col.s2.text-right= link_to "<i class='material-icons'>delete_forever</i>".html_safe,  { action: "destroy", id: @event.id }, method: :delete, :class => "btn waves-effect waves-light amber", data: { confirm: "Are you sure?" } if can? :destroy, @event

%h4= event_dtg(@event)
%p
  %b Description:
  = @event.description

%h4 Leaves
.row
  = leaf_header(@event)

app/views/events/_old.html.haml
= simple_form_for(@event, :url => "/events", :method => :post) do |f|
  = f.error_notification
  .form-inputs
    .form-group
      = f.input :name
    .form-group
      / = f.association :location
  
    %h3 Leaves
    .row
      .col-xs-3
        = leaf_form(f,:heritage)
      .col-xs-3
        = leaf_form(f,:hobbies)
      .col-xs-3
        = leaf_form(f,:life_skills)
      .col-xs-3
        = leaf_form(f,:outdoor_activities)
    .row
      .col-xs-3
        = leaf_form(f,:pioneer_skills)
      .col-xs-3
        = leaf_form(f,:sci_tech)
      .col-xs-3
        = leaf_form(f,:values)
      .col-xs-3
        = f.input :service

    = f.input :starts_at, as: :string
    = f.input :description

  .form-actions
    = f.button :submit
    or
    = link_to "Cancel", :back

:javascript
  $('#event_starts_at').datetimepicker({dateFormat: "yy-mm-dd"});

app/views/events/edit.html.haml
%h1= "Editing '#{@event.name}'"

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
.row.valign-wrapper
  .col.s12.m8.valign
    =title(@title)
  .col.s12.m4.valign.right-align
    = link_to micon('add'), new_event_path, {class: 'btn-floating btn-large waves-effect waves-light'} if can? :create, Event

.row.center-align
  = paginate @events

%table.striped.bordered
  %thead
    %tr
      %th Event
      %th.text-center Date
      %th.text-center= tooltip('S','Service Hours')
      %th.text-center= tooltip('H','Heritage')
      %th.text-center= tooltip('B','Hobbies')
      %th.text-center= tooltip('L','Life Skills')
      %th.text-center= tooltip('O','Outdoor Activities')
      %th.text-center= tooltip('P','Pioneering Skills')
      %th.text-center= tooltip('T','Science & Technology')
      %th.text-center= tooltip('V','Values')

  = render :partial => @events

app/views/events/new.html.haml
= title("Create New Event")

= render 'form'

app/views/events/show.html.haml
= render :partial => "events/header"

%h2 Roster

%h3 Present

%div#present
  = render :partial => 'attendances/attendance', :collection => @attendees

- if can? :edit, @event      
  %h3 Absent

  %div#absent
    =render :partial => "events/candidates"